# Generated by Django 5.0.6 on 2026-06-21 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', '创建'), ('status_changed', '状态变更'), ('field_changed', '信息修改'), ('borrowed', '借出'), ('returned', '归还')], max_length=32, verbose_name='变更类型')),
                ('field_name', models.CharField(blank=True, max_length=64, verbose_name='字段名')),
                ('old_value', models.TextField(blank=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('description', models.CharField(max_length=255, verbose_name='变更描述')),
                ('operator', models.CharField(blank=True, max_length=60, verbose_name='操作人')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('borrow_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='licenses.borrowrecord', verbose_name='借还记录')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='licenses.license', verbose_name='证照')),
            ],
            options={
                'verbose_name': '证照变更记录',
                'verbose_name_plural': '证照变更记录',
                'ordering': ['-change_date', '-id'],
            },
        ),
    ]
